### ISSUE TITLE
除了查询，其它插入、更新都不行

### ISSUE THREAD

**Issue by tomener** [johng-cn/gf#2]
```
package main

import (
	"gitee.com/johng/gf/g/database/gdb"
	"fmt"
)

var db *gdb.Db

func init()  {
	gdb.AddDefaultConfigNode(gdb.ConfigNode {
		Host    : "127.0.0.1",
		Port    : "3306",
		User    : "root",
		Pass    : "123456",
		Name    : "test",
		Type    : "mysql",
		Role    : "master",
		Charset : "utf8",
	})
	var err error
	db, err = gdb.Instance()
	checkErr(err)
}

func main() {
	query()
	insert()
}

// 基本sql查询
func query() {
	fmt.Println("query:")
	list, err := db.GetAll("select * from user limit 2")
	if err == nil {
		fmt.Println(list)
	} else {
		fmt.Println(err)
	}
	fmt.Println()
}

// 数据写入
func insert() {
	fmt.Println("insert:")
	r, err := db.Insert("user", gdb.Map {
		"name": "john",
	})
	if err == nil {
		uid, _ := r.LastInsertId()
		fmt.Println(uid)
	} else {
		fmt.Println(err)
	}
	fmt.Println()
}

func checkErr(err error) {
	if err != nil {
		panic(err)
	}
}
```

**输出如下：**

```
query:
[map[email:take@qq.com type:1 uid:1 name:take] map[uid:14 name:flume email:flume@qq.com type:1]]

insert:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xf0 pc=0x60bb92]

goroutine 1 [running]:
gitee.com/johng/gf/g/database/gdb.(*Db).Exec(0xc04203e200, 0xc042064870, 0x21, 0xc042036c40, 0x1, 0x1, 0x21, 0x1, 0x4, 0x0)
        D:/Goworks/src/gitee.com/johng/gf/g/database/gdb/gdb_base.go:51 +0x72
gitee.com/johng/gf/g/database/gdb.(*Db).insert(0xc04203e200, 0x68db07, 0x4, 0xc042064840, 0xc042072400, 0x0, 0x0, 0x0, 0x0)
        D:/Goworks/src/gitee.com/johng/gf/g/database/gdb/gdb_base.go:205 +0xc34
gitee.com/johng/gf/g/database/gdb.(*Db).Insert(0xc04203e280, 0x68db07, 0x4, 0xc042064840, 0xc042064840, 0x0, 0x0, 0x0)
        D:/Goworks/src/gitee.com/johng/gf/g/database/gdb/gdb_base.go:210 +0x64
main.insert()
        D:/Goworks/src/edition/b.go:48 +0x1d4
main.main()
        D:/Goworks/src/edition/b.go:28 +0x2c
exit status 2
```

**user表结构：**

```
CREATE TABLE `user` (
  `uid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(30) NOT NULL DEFAULT '' COMMENT '昵称',
  `email` varchar(60) NOT NULL DEFAULT '' COMMENT '邮箱',
  `type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '订单',
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

**Comment by johng-cn** [comment]
问题已修复，请查看：https://gitee.com/johng/gf/issues/IISWI
